name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        cd $GITHUB_WORKSPACE |
        echo "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin\MSBuild.exe  RomanCalc.sln /p:Configuration=Release /p:Platform=x64"
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe"  RomanCalc.sln /p:Configuration=Release /p:Platform=x64
    
    - uses: actions/upload-artifact@master
      with:
        name: exe
        path: $GITHUB_WORKSPACE\bin\x64\Release\RomanCalc.exe
